# hadolint ignore=DL3006
FROM istionightly/base_debug

#ADD https://dl.k8s.io/v1.13.0/kubernetes-client-linux-amd64.tar.gz /
ADD https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl /usr/bin/kubectl
RUN chmod +x /usr/bin/kubectl

COPY nsm_svc_reg /usr/bin/nsm_svc_reg

CMD [ "/usr/bin/nsm_svc_reg", "pod-watcher", "--kubeconfig", "$KUBECONFIG", "--kubeconfigremote", "$KUBECONFIGREMOTE" ]
